password: 1GHGjhggb5564#$%
encrypt_type: aes
target_paths:
- /persistent/home/andy/Wallpapers
- /persistent/home/andy/测试
- /persistent/home/andy/测试1
obfuscate_suffix: .dat
obfuscate_name_length: 12
map_filename: .app_encrypt
lock_filename: .encrypt.lock
map_storage_path: /home/andy/Downloads/encrypt/tmp
